name: Ruby Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: '2.7.7'
            gemfile: 'rails_5_2'
          - ruby-version: '3.0.5'
            gemfile: 'rails_6_1'
          - ruby-version: '3.0.5'
            gemfile: 'rails_7'
          - ruby-version: '3.1.3'
            gemfile: 'rails_6_1'
          - ruby-version: '3.1.3'
            gemfile: 'rails_7'
          - ruby-version: '3.2.0'
            gemfile: 'rails_6_1'
          - ruby-version: '3.2.0'
            gemfile: 'rails_7'

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
